dist: xenial
language: python

notifications:
  email:
    recipients:
      - jpaynter@student.unimelb.edu.au
    on_success: change
    on_failure: always

matrix:

  include:
    - os: linux
      python: 3.7

    #- os: osx
    #  python: 3.7 # Should be a string version, e.g., "3.6".
    #  osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
    #  language: generic # 'language: python' is an error on Travis CI macOS

before_install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pytest pytest-cov
  - pip install codecov
  #- pip install coverage

install:
  - python setup.py sdist bdist_wheel

script:
  - pytest --cov

after_success:
  - codecov
  #- curl -s https://codecov.io/bash | bash
  # https://github.com/codecov/codecov-bash/issues/94 codecov errors re: bash

# https://github.com/codecov/example-python
