#!/bin/bash
#
#SBATCH --job-name=array_job
#SBATCH --output=array_job_3770_output.txt
#SBATCH --error=array_job_3770_errors.txt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=144:00:00
#SBATCH --array=1-32
## SBATCH --mem-per-cpu=4000

#%Module module load Python/3.7.3-spartan_gcc-8.1.0
#%Module module load numpy/1.18.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load scipy/1.3.0-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load matplotlib/3.1.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load pandas/0.24.2-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load xlrd/1.2.0-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load dynesty/1.0.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load pymultinest/2.7-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load corner/2.0.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load bilby/0.5.9-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load astropy/3.2.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load prettytable/0.7.2-Python-3.7.3-spartan_gcc-8.1.0

index=(8 9 10 11 12 13 14 15 24 25 26 27 28 29 30 31)

python /data/projects/punim1050/PyGRB_Bayes/PyGRB_Bayes/scripts/run_3770.py -i ${index[${SLURM_ARRAY_TASK_ID}-1]} --HPC
