#!/bin/bash
#
#SBATCH --job-name=array_job
#SBATCH --output=array_job_3770_tte_output_%A_%a.txt
#SBATCH --error=array_job_3770_tte_errors_%A_%a.txt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=144:00:00
#SBATCH --array=1-64
## SBATCH --mem-per-cpu=16000

#%Module module load Python/3.7.3-spartan_gcc-8.1.0
#%Module module load numpy/1.18.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load scipy/1.3.0-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load matplotlib/3.1.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load pandas/0.24.2-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load xlrd/1.2.0-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load dynesty/1.0.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load pymultinest/2.7-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load corner/2.0.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load bilby/0.5.9-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load astropy/3.2.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load prettytable/0.7.2-Python-3.7.3-spartan_gcc-8.1.0

index=(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63)

python /data/projects/punim1050/PyGRB/PyGRB/scripts/run_3770_tte.py -i ${index[${SLURM_ARRAY_TASK_ID}-1]} --HPC
