#!/bin/bash
#
#SBATCH --job-name=MC_analysis
#SBATCH --output=MC_output.txt
#SBATCH --error=MC_errors.txt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=144:00:00
#SBATCH --array=1-24
## SBATCH --mem-per-cpu=4000

#%Module module load Python/3.7.3-spartan_gcc-8.1.0
#%Module module load numpy/1.16.4-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load matplotlib/3.1.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load dynesty/1.0.0-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load pymultinest/2.7-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load corner/2.0.1-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load bilby/0.5.6-Python-3.7.3-spartan_gcc-8.1.0
#%Module module load astropy/3.2.1-Python-3.7.3-spartan_gcc-8.1.0

index=(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23)

python /data/projects/punim1050/PyGRB_Bayes/PyGRB_Bayes/core/DynamicBilby.py -i ${index[${SLURM_ARRAY_TASK_ID}-1]} --HPC
